eval $(ssh-agent)
ssh-add ~/.ssh/rmitGitHub
export PATH="$HOME/bin:$PATH"

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
export HELIX_RUNTIME=$(dirname $(which hx))/../share/helix/runtime
